version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker    
      - run:
          name: Create a new release
          command: |
            chmod +x version-git.sh 
            export VERSION=`./version-git.sh`
            # Tagging
            git tag -a $VERSION -m "version $VERSION"
            
            export OWNER=MonseGuzman
            export REPOSITORY=pipeline-test
          
            curl --data '{"tag_name": "$VERSION",
                            "target_commitish": "master",
                            "name": "$VERSION",
                            "body": "Release of version $VERSION",
                            "draft": false,
                            "prerelease": false}' \
                https://api.github.com/repos/$OWNER/$REPOSITORY/releases?access_token=${GITHUB_TOKEN}
