version: 2.1
workflows:
  project:
    jobs:
      - "release":
          requires:
orbs:
  github-release: h-matsuo/github-release@0.1.1
jobs:
  "release":
    description: Create a publish a new release.
    executor: github-release/default
    steps:
      - checkout
      - run:
          name: Export environment variables
          command: |
            chmod +x version-git.sh
            echo export $(VERSION=`./version-tag.sh`) >> $BASH_ENV
      # - run:
      #     name: Create artifacts
      #     command: |
      #       mkdir artifacts
      #       echo dummy > ./artifacts/release
      - github-release/create:
          tag: $VERSION
          title: $VERSION
          description: Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
          # file-path: ./artifacts/release
