version: 2.1
workflows:
  project:
    jobs:
      - "build"
orbs:
  github-release: h-matsuo/github-release@0.1.1
jobs:
  "build":
    description: Create a publish a new release.
    executor: github-release/default
    steps:
      - checkout
      - run:
          name: Export environment variables
          command: |
            export VER=$(git tag | sort -V | tail -1)
            export DESCRI=`cat description.txt`

            echo "export VERSION=${VER}" >> $BASH_ENV
            echo "export DESCR='${DESCRI}'" >> $BASH_ENV
      - github-release/create:
          tag: $VERSION
          title: version $VERSION
          description: $DESCR
          # file-path: ./artifacts/file
