version: 2.1
workflows:
  project:
    jobs:
      - "build"
      - "release":
          requires:
            - "build"
orbs:
  github-release: h-matsuo/github-release@0.1.1
jobs:
  "build":
    docker: 
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker    
      - run:
          name: Create a new tag
          command: |
            echo "does not work, for now"
            # chmod +x version-git.sh 
            # export VERSION=`./version-git.sh`
            # # Tagging
            # git tag -a $VERSION -m "version $VERSION"
            # git push "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/MonseGuzman/pipeline-test.git" --tags
  "release":
    description: Create dummy file and publish a new release.
    executor: github-release/default
    steps:
      - checkout
      - run:
          name: Export environment variables
          command: |
            echo export $(grep -v '^#' dwarf.config | xargs) >> $BASH_ENV
      - run:
          name: Create artifacts
          command: |
            mkdir artifacts
            echo dummy > ./artifacts/release
      - github-release/create:
          tag: $CI_VERSION
          title: This is the release $CI_VERSION
          description: hey, esto es un release o tag?
          file-path: ./artifacts/release
