version: 2.1
workflows:
  project:
    jobs:
      - "build"
      - "release"
          requires:
            - "build"
jobs:
  "build":
    docker: 
      - image: circleci/cci-demo-docker-primary:0.0.2
    steps:
      - checkout # check out the code in the project directory
      - setup_remote_docker    
      - run:
          name: Create a new release
          command: |
            chmod +x version-git.sh 
            export VERSION=`./version-git.sh`
            # Tagging
            git tag -a $VERSION -m "version $VERSION"
            git push "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/MonseGuzman/pipeline-test.git" --tags
  "release":
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run:
          name: Export environment variables
          command: |
            echo export $(grep -v '^#' dwarf.config | xargs) >> $BASH_ENV
      - run:
          name: Install package
          command: |
            go get github.com/github-release/github-release
      - run:
          name: Create release
          command: |
            chmod +x release.sh
            ./release
